config/urls.py
from django.contrib import admin
from django.contrib.auth.views import (PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from core.views import Index, landing, legal
from match.views import (CreateMatchView, MatchDetailView,
                         MatchInProgressListView, MatchOverListView,
                         MatchPlannedListView,
                         MatchSubscriptionInProgressListView,
                         MatchSubscriptionOverListView,
                         MatchSubscriptionPlannedListView, UpdateMatchView,
                         cancel_match, kick_player)
from notifications.views import NotificationListView, delete_notification
from player.ajax_view import player_follow
from player.views import (PlayerInvitationListView, accept_match_invitation,
                          cancel_match_request, decline_match_invitation,
                          decline_match_request)
from search_manager.ajax_view import (autocomplete_city, autocomplete_player,
                                      filter_match_view, filter_player_view,
                                      get_user_current_coordinates)
from search_manager.views import (SearchMapMatchView, SearchMapPlayerView,
                                  SearchTableMatchView)
from users.views import (CustomLoginView, CustomLogoutView, ProfileView,
                         RegisterView, UserSettingsView)

urlpatterns = [
    path('', landing, name='landing'),
    path('legal/', legal, name='legal'),
    path('admin/', admin.site.urls),
    path('index/', Index.as_view(), name='index'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/reset_password.html'), name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='users/reset_password_done.html'), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/reset_password_confirm.html'), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
         template_name='users/reset_password_complete.html'), name='password_reset_complete'),
    path('profile/<slug:username>', ProfileView.as_view(), name='profile'),
    path('settings/profile', UserSettingsView.as_view(), name='settings-profile'),
    path('match/create/', CreateMatchView.as_view(), name='match-creation'),
    path('match/update/<int:pk>', UpdateMatchView.as_view(), name='match-update'),
    path('match/list/planned', MatchPlannedListView.as_view(), name='match-planned'),
    path('match/list/over', MatchOverListView.as_view(), name='match-over'),
    path('match/list/in-progress', MatchInProgressListView.as_view(),
         name='match-in-progress'),
    path('match/subscription/list/planned',
         MatchSubscriptionPlannedListView.as_view(), name='match-subscription-planned'),
    path('match/subscription/list/over',
         MatchSubscriptionOverListView.as_view(), name='match-subscription-over'),
    path('match/susbscription/list/in-progress', MatchSubscriptionInProgressListView.as_view(),
         name='match-subscription-in-progress'),
    path('match/detail/<int:pk>/', MatchDetailView.as_view(), name='match-detail'),
    path('search/map/match/', SearchMapMatchView.as_view(), name='search-map-match'),
    path('search/table/match/', SearchTableMatchView.as_view(),
         name='search-table-match'),
    path('search/map/player/', SearchMapPlayerView.as_view(),
         name='search-map-player'),
    path('search/match/filter', filter_match_view, name='filter-match'),
    path('search/player/filter', filter_player_view, name='filter-player'),
    path('autocomplete', autocomplete_city, name='city-autocomplete'),
    path('player-autocomplete', autocomplete_player, name='player-autocomplete'),
    path('player/follow', player_follow, name='player-follow'),
    path('current_coordinates', get_user_current_coordinates,
         name='current-coordinates'),
    path('player/invitations/', PlayerInvitationListView.as_view(),
         name='player-invitations'),
    path('cancel_match_request/<int:pk>/',
         cancel_match_request, name='cancel-match-request'),
    path('decline_match_request/<int:pk>/',
         decline_match_request, name='decline-match-request'),
    path('decline_match_invitation/<int:pk>/', decline_match_invitation,
         name='decline-match-invitation'),
    path('accept_match_invitation/<int:pk>/', accept_match_invitation,
         name='accept-match-invitation'),
    path('cancel_match/<int:pk>/', cancel_match,
         name='cancel-match'),
    path('remove-player/<int:pk>/', kick_player, name='remove-player'),
    path('notifications/', NotificationListView.as_view(),
         name='notifications'),
    path('notifications/delete/<int:pk>',
         delete_notification, name='delete-notification'),
]

handler404 = 'core.views.custom_page_not_found_view'

notifications/models/notification.py
from django.db import models

from notifications.managers.notification_manager import NotificationManager
from users.models.user import User


class Notification(models.Model):

    NOTIFICATIONS_TYPE = ((1, 'invitation-send'),
                          (2, 'invitation-accepted'),
                          (3, 'follow'))

    from_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='noti_from_user', blank=True, default=None)
    to_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='noti_to_user', blank=True,  default=None)

    notification_type = models.IntegerField(choices=NOTIFICATIONS_TYPE)

    text_preview = models.CharField(max_length=90, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    is_read = models.BooleanField(default=False)

    objects = NotificationManager()

notifications/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic.list import ListView

from .models.notification import Notification


class NotificationListView(LoginRequiredMixin, ListView):
    model = Notification
    template_name = 'notifications/notifications.html'

    def get_queryset(self):

        notifications_qs = Notification.objects.get_notif_for_user_by_date(
            self.request.user)

        notifications_qs.update(is_read=True)

        return notifications_qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


@login_required
def delete_notification(request, pk):
    notification = Notification.objects.get_notif_for_user(
        id=pk, to_user=request.user)

    notification.delete()

    return redirect("notifications")

notifications/templates/notifications/notifications.html
{% extends "core/base.html" %}

{% load static %}
{% load humanize %}
{% block content %}
<div class="card">
    <div class="card-body">
        <div class="overflow-scroll">

            {% if notification_list|length == 0 %}

            <div class="alert alert-primary" role="alert">
                Vous n'avez pas de notifications!
            </div>

            {% else %}


            {% for notification in notification_list %}

            {% if notification.notification_type == 1 %}

            <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header bg-danger text-white">
                    <i data-feather="alert-circle"></i>
                    <strong class="mr-auto">Invitation pour un match</strong>
                    <small class="text-white-50 ml-2">{{ notification.date|naturaltime }}</small>
                    <a href="{% url 'delete-notification' notification.id %}" class="ml-2 mb-1 close text-white"
                        type="button" data-dismiss="toast" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </a>
                </div>
                <div class="toast-body">
                    <strong>@{{ notification.from_user.username }}</strong>
                    <br>
                    <p><i class="fas fa-user-plus"></i> vous invite pour un match!</p>
                </div>
            </div>

            {% endif %}

            {% if notification.notification_type == 2 %}

            <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header bg-success text-white">
                    <i data-feather="alert-circle"></i>
                    <strong class="mr-auto">Invitation acceptée</strong>
                    <small class="text-white-50 ml-2">{{ notification.date|naturaltime }}</small>
                    <a href="{% url 'delete-notification' notification.id %}" class="ml-2 mb-1 close text-white"
                        type="button" data-dismiss="toast" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </a>
                </div>
                <div class="toast-body">
                    <strong>@{{ notification.from_user.username }}</strong>
                    <br>
                    <p><i class="fas fa-user-plus"></i> a accepté votre invitation!</p>
                </div>
            </div>

            {% endif %}

            {% if notification.notification_type == 3 %}

            <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header bg-primary text-white">
                    <i data-feather="alert-circle"></i>
                    <strong class="mr-auto">Nouvel abonné</strong>
                    <small class="text-white-50 ml-2">{{ notification.date|naturaltime }}</small>
                    <a href="{% url 'delete-notification' notification.id %}" class="ml-2 mb-1 close text-white"
                        type="button" data-dismiss="toast" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </a>
                </div>
                <div class="toast-body">
                    <strong>@{{ notification.from_user.username }}</strong>
                    <br>
                    <p><i class="fas fa-user-plus"></i> vous suit!</p>
                </div>
            </div>

            {% endif %}
            {% endfor %}
            {% endif %}

        </div>

    </div>
</div>
<br>
{% endblock content %}